version: '3.9'
services:

  backend:
    build: 
      context: ./backend/sistema-inscricao-de-materias/
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - matricula-network
  
  frontend:
    build:
      context: ./frontend/sistema_matricula/
    ports:
      - "3000:80"
    networks:
      - matricula-network
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - matricula-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  matricula-network:
    driver: bridge

volumes:
  postgres-data: