CREATE TABLE IF NOT EXISTS public.aluno
--CREATE TABLE IF NOT EXISTS aluno
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ano_ingressao date,
    nome_completo character varying(255) COLLATE pg_catalog."default",
    nota_geral integer NOT NULL,
    prioridade boolean NOT NULL,
    CONSTRAINT aluno_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.materia
--CREATE TABLE IF NOT EXISTS materia
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    capacidade_maxima integer NOT NULL,
    nome_materia character varying(255) COLLATE pg_catalog."default",
    tem_espaco boolean NOT NULL,
    CONSTRAINT materia_pkey PRIMARY KEY (id)
);

--CREATE TABLE IF NOT EXISTS public.aluno_materia
CREATE TABLE IF NOT EXISTS aluno_materia
(
    aluno_id bigint NOT NULL,
    materia_id bigint NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT fkbf5pcj4gcd42mqdu68exubyqm FOREIGN KEY (materia_id)
--        REFERENCES materia (id) MATCH SIMPLE
        REFERENCES public.materia (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fktj3ao3hbin3on9r539m9j7vca FOREIGN KEY (aluno_id)
--        REFERENCES aluno (id) MATCH SIMPLE
        REFERENCES public.aluno (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);